### ISSUE TITLE
Styling child elements

### ISSUE THREAD

**Issue by amontin** [eiriklv/react-masonry-component#10]
I can't figure out what I'm doing wrong. My code below is almost identical to the example given, but I'm trying to style the child elements of the Masonry component. The problem is that transitions don't work with the current styling. If I remove the "height" property and only use "width", transitions do work! Can anyone help? (I'm using the latest Chrome browser.)
````
import React from 'react';
var Masonry = require('react-masonry-component')(React);

var masonryOptions = {
    transitionDuration: '0.6s',
    columnWidth: 200
};

class Container extends React.Component {
        
    render() {
        
        let style = { width: 180, height: 180 };  //**** styling seems to cause trouble 
       
         let urls = ["../img/worksheet.jpg", "../img/activity.jpg"];

        let childElements = urls.map((url,idx)=>{
            return <img key={idx} style={style} src={url} />;
        });

        return (
            <Masonry
                className={''} // default ''
                elementType={'div'} // default 'div'
                options={masonryOptions} // default {}
                disableImagesLoaded={false} // default false
            >
                {childElements}
            </Masonry>
        )
	}

}

export default Container; 
````

**Comment by amontin** [comment]
So using maxHeight instead of height seems to do the trick. However if I wrap the image child elements in some other element like a div the transitions don't work. Since I don't really require a lot of masonry's functionality, I've switched to a simple flexbox layout to order my tiles instead.

**Comment by eiriklv** [comment]
Flexbox is really good! Unfortunately it doesn't allow you to have variable height for your elements like you do with Masonry :-)

**Comment by afram** [comment]
Closing issue as is a Masonry issue and not related to this component. @amontin please reopen if you want to discuss further.
