### ISSUE TITLE
0px sized items when wrapped

### ISSUE THREAD

**Issue by moimael** [eiriklv/react-masonry-component#100]
Wrapping react-masonry-component in a div causes the masonry grid to render with items having 0px height and width.

As soon as i remove the wrapping div everything works as intended.

Any workaround ?

Thanks !

**Comment by afram** [comment]
Hi @moimael Could you provide an example?

In this sample code react-masonry-component is wrapped by an outer DIV and it works fine - I'm need a bit more info about your specific use case :-)

https://www.webpackbin.com/bins/-KnBuUxuxu9B16Cr1ED5
