### ISSUE TITLE
Need help with Append

### ISSUE THREAD

**Issue by DeathDealerr** [eiriklv/react-masonry-component#102]
Hi,

I request you help in appending new set of items by accessing the Masonry Instance.

My Main Component
```
<Masonry className={'row'} // default ''

  elementType={'div'} // default 'div'

  options={masonryOptions} // default {}

  disableImagesLoaded={false} // default false

  updateOnEachImageLoad={false} // default false and works only if disableImagesLoaded is false

  ref={function(c) {
        this.masonry = this.masonry || c.masonry;
      }.bind(this)}>
        {this.renderItems()}
      </Masonry>
    );
  }
}
```

under component did mount i did the following 
```
console.log(this.masonry);
//items is new array of items
this.masonry.append(items).masonry('appended',items);
```

I am not sure if i am doing it right, Please help me with an example

**Comment by afram** [comment]
@DeathDealerr 

You don't use the underlying Masonry object to add items. You need to add items to the object return by calling `this.renderItems()` if that makes sense.

**Comment by DeathDealerr** [comment]
@afram ,

Thank you for the help.
