### ISSUE TITLE
Can't click inside an item

### ISSUE THREAD

**Issue by kaloudiyi** [eiriklv/react-masonry-component#104]
I would like manage the click inside an item and update some of their properties. The events doesn't respond when there are located inside items. It's difficult to do that with the only one onClick event of the Masonry component.

How can I do this ?

**Comment by afram** [comment]
Hi @kaloudiyi 

You should be able to attach event listeners to each item. Do you have a code sample we can refer to?

**Comment by kaloudiyi** [comment]
I wrote a simple example and "good surprise for me" it worked.  So the problem is in my code. Thanks :-)
