### ISSUE TITLE
Centering Masonry

### ISSUE THREAD

**Issue by xih** [eiriklv/react-masonry-component#107]
Hi, 

I love the results from using this package ! Thanks for making it. 

But I'm having trouble centering Masonry. I tried using flexbox and bootstrap to make the component horizontally centered but to no avail. This is how it looks on my macbook: 

![image](https://user-images.githubusercontent.com/8076886/32949654-81843436-cb58-11e7-8fda-1f7ad63a33a4.png)

As you can see there is too much space on the left side. How can I fix this ? 

Cheers

**Comment by burt23** [comment]
I'm having the same exact issue, any help is greatly appreciated

**Comment by mayankagarwal2402** [comment]
This solution here (https://github.com/eiriklv/react-masonry-component/issues/31#issuecomment-236036096) works fine.

**Comment by erosenberg** [comment]
@mayankagarwal2402 - this no longer works. Is there an update for this?
