### ISSUE TITLE
Children Resize

### ISSUE THREAD

**Issue by amason0528** [eiriklv/react-masonry-component#115]
I'm using this React-mansory-component library and it's very useful except one thing.

The height of my elements in the layout can be increased or decreased (It has edit button and if it is clicked, the edit form appears at the bottom of element)

In this case, Mansory changes the position of elements. I want to stop this.

Please let me know the solution for this.

**Comment by afram** [comment]
Have you tried the stamp method from Masonry?

**Comment by Mike-Timms** [comment]
> I'm using this React-mansory-component library and it's very useful except one thing.
> 
> The height of my elements in the layout can be increased or decreased (It has edit button and if it is clicked, the edit form appears at the bottom of element)
> 
> In this case, Mansory changes the position of elements. I want to stop this.
> 
> Please let me know the solution for this.

Add the prop enableResizableChildren={true}.

<Masonry enableResizableChildren={true}></Masonry>
