### ISSUE TITLE
ImagesLoaded not working on background-images

### ISSUE THREAD

**Issue by alberto2000** [eiriklv/react-masonry-component#121]
Is there a way to tell ImagesLoaded to also trigger on background-images?

**Comment by afram** [comment]
@alberto2000 currently the background images feature of the `imagesloaded` library is not used. 

We'd have to change this library to support it.

**Comment by alberto2000** [comment]
afaik it's just an option, can it just be enabled by default?

**Comment by afram** [comment]
That's changing the current behaviour, so I'm a bit hesitant as it's not backwards compatible and technically should be a breaking change version bump (major version). 

imagesloaded doesn't have this feature on by default either. I think a better design would be to allow end users to provide config for imagesloaded (in a backwards compatible way fo course).

**Comment by alberto2000** [comment]
Totally agree. Why not let users provide the config for imagesloaded to the react-masonry component?

**Comment by afram** [comment]
Yeah that's what I'm thinking too

**Comment by afram** [comment]
@alberto2000 can you please try with this pre-release version?

`npm install -S react-masonry-component@pre-6.1.0`

The ReadMe for this version is available here:
https://github.com/eiriklv/react-masonry-component/tree/imagesloaded-config#images-loaded-options

**Comment by alberto2000** [comment]
@afram did you just release 6.1.0 upstream? Did a npm update in my project and it fetched react-masonry-component@6.1.0. Thanks a lot, will try it later today

**Comment by afram** [comment]
I have only released as a pre-release. 

If you npm install you should get the version tagged as latest (6.0.2). 
npm update will then give you 6.1.0. Perhaps I should have tagged it as `next` instead.

Please let me know how you get on and then I can release it to latest.

**Comment by alberto2000** [comment]
Hey, sorry for the late reply. It works great!

**Comment by afram** [comment]
great thanks. 6.1.1 published.
