### ISSUE TITLE
Incompatible properties in the interface of MasonryOptions (columnWidth, transitionDuration)

### ISSUE THREAD

**Issue by maxkoshel** [eiriklv/react-masonry-component#123]
#According to the [documentation of Masonry](https://masonry.desandro.com/options.html) there are some issues:
* Property `columnWidth` can accept also `Element`.
* Property `transitionDuration` can also accept `number` (zero for disabling).

**Comment by afram** [comment]
Thanks for submitting this. It has bee merged and 6.2.0 published.
