### ISSUE TITLE
🚑 Critical bug in componentWillUnmount that breaks the app

### ISSUE THREAD

**Issue by A-Tokyo** [eiriklv/react-masonry-component#129]
## Description
When `disableImagesLoaded` is true, `componentWillUnmount` throws `this.imagesLoadedCancelRef is not a function`

### How to reproduce
- Pass `disableImagesLoaded` prop, render then unmount the component.

### Fix
- Only call `derefImagesLoaded` in `componentWillUnmount` if `imagesLoadedCancelRef` was truthy.

<img width="556" alt="screen shot 2018-05-29 at 6 58 51 am" src="https://user-images.githubusercontent.com/12428415/40638815-cc2cba92-630d-11e8-9407-552783509e82.png">

### PR: https://github.com/eiriklv/react-masonry-component/pull/128

**Comment by roruva** [comment]
Hi, I have the same issue, what did you do to solve it? thanks in advance.

**Comment by A-Tokyo** [comment]
@roruva I had to not use `disableImagesLoaded ` for now :/ 

I opened a PR that fixes it, hopefully it gets merged soon 👍

**Comment by afram** [comment]
6.2.1 should be published. Apologies for the delay and thanks for the contribution
