### ISSUE TITLE
Hearsay.me source

### ISSUE THREAD

**Issue by clearly** [eiriklv/react-masonry-component#13]
Would be really useful if the original source for the hearsay.me live demo was somehow included here.

**Comment by clearly** [comment]
NM...found the other project that refers here. But it is based on the Mixin use.

Have tried to stay away from mixin based approaches: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.ryxgrprpf

**Comment by eiriklv** [comment]
Hi @clearly! I know - it should be rewritten to use the component version :-) Feel free to send a PR if you get to it before i do.
