### ISSUE TITLE
Demo app does not work in uplevel browsers

### ISSUE THREAD

**Issue by nickytonline** [eiriklv/react-masonry-component#131]
Hi @eiriklv. Thanks for the project. Just a heads up that the demo app on Heroku does not work because your API calls are not HTTPS, so the browsers complain about mixed content. Just thought you might want to know. Cheers.

<img width="1920" alt="screen shot 2018-07-04 at 1 14 00 pm" src="https://user-images.githubusercontent.com/833231/42289240-69545de4-7f8c-11e8-9814-d22fbf12435b.png">

**Comment by NoahFrank** [comment]
Demo was fixed today (4/3/2019) after shooting Eirik an email about the issue!
