### ISSUE TITLE
Matches-selector update breaks this

### ISSUE THREAD

**Issue by thgil** [eiriklv/react-masonry-component#15]
You get this error when you load this component now.
`Uncaught TypeError: elem[matchesMethod] is not a function`

I think its because https://github.com/desandro/matches-selector got updated to v2.0.0

**Comment by kenotron** [comment]
I'm hitting this as well. The idea of taking a github.com/desandro/matches-selector as dependency instead of pegging to a MAJOR version is risky at best. Also, not sure why use so much of your own forks of @desandro 's software?

**Comment by eiriklv** [comment]
@thgil @kenotron See https://github.com/eiriklv/react-masonry-component/issues/14

**Comment by afram** [comment]
@thgil @kenotron this should be fixed now - can please you try installing again?

**Comment by thgil** [comment]
@afram Thanks a lot, it's working again.
