### ISSUE TITLE
Update to React 17

### ISSUE THREAD

**Issue by TheOneAndOnlyGarcia** [eiriklv/react-masonry-component#156]
if possible, it would be nice if the package.json could be updated to react 17.

**Comment by mgreca** [comment]
I've created a PR for this #157

**Comment by doverradio** [comment]
@mgreca I see you had found no conflicts.  

However, I just tried adding this to a project with react@17.0.2

Result: 
```
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0-0" from react-masonry-component@6.2.1
npm ERR! node_modules/react-masonry-component
npm ERR!   react-masonry-component@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Is there any way to solve this error and use this `react-masonry-component`?

**Comment by mgreca** [comment]
@doverradio the PR #157 solves that issue but is not merged, we need @eiriklv to merge it and release a new version.

**Comment by afram** [comment]
It's merged and published, though looks like there are quite a few outdated packages. I don't have a lot of time these days sorry, but if someone were to update the dependencies, I'll review and merge.
