### ISSUE TITLE
How do you bind to masonry events?

### ISSUE THREAD

**Issue by ads1018** [eiriklv/react-masonry-component#16]
I'd like to change the state of my app once the masonry layout is complete but that requires binding to the event listener "layoutComplete". Does this component provide an instance to the masonry object for event binding?

**Comment by afram** [comment]
@ads1018 Yes this component provides access to a `masonry` property on the React class, you can access it using refs.

es6
```js
class Container extends React.Component {
    render() {
        return <Masonry ref={c => this.masonry = c.masonry}> ... </Masonry>
    }

    componentDidMount() {
        this.masonry.on('layoutComplete', () => {})
    }    
}
```

**Comment by ads1018** [comment]
Fantastic. Thanks @afram

**Comment by afram** [comment]
I'm going to close this, please reopen if you have any further issues related to this.

**Comment by himat** [comment]
How do you do this when using react hooks?
