### ISSUE TITLE
Investigate usage in Meteor

### ISSUE THREAD

**Issue by afram** [eiriklv/react-masonry-component#17]
It seems that there are issues using this with Meteor. Need to solve the pain points and update component/readme

**Comment by dcworldwide** [comment]
What are the problems you've encountered? Seems to work ok for me...

**Comment by afram** [comment]
In truth, I am not a Meteor dev and have based this exploration on users feedback. I haven't had a chance to look at this in depth yet, though I'm curious if you had to do anything special to get it working?

Would you be interested in submitting a PR for a few lines of documentation around the process?

**Comment by dcworldwide** [comment]
I actually didn't do anything special. Just npm installed and setup as per the readme. If I do find issues I'll post here

**Comment by afram** [comment]
closing as not an issue
