### ISSUE TITLE
Is there any way to sort the order of elements using this component? 

### ISSUE THREAD

**Issue by pvijeh** [eiriklv/react-masonry-component#19]

**Comment by afram** [comment]
react-masonry-component does not sort it's contents, you have to provide sorted child elements.

Here is a hypothetical example where we put some child elements in descending order. I've left out any non essential details like class names etc.

For this example, `props.someElementsArray` contains items that are strings, eg:
```json
["foo", "bar", "baz"]
```

```jsx
React.createClass({
    render: function() {
        var children = this.props.someElementsArray
            .sort()
            .reverse()
            .map(function(child) {
                return <div>{child}</div>
            });

        return (
            <Masonry>{children}</Masonry>
        );
    }
});
```

The above code will render something like

```html
<div>
    <div>bar</div>
    <div>baz</div>
    <div>foo</div>
</div>
```

**Comment by afram** [comment]
I'm going to close this ticket due to inactivity. Please reopen if you would like to discuss further
