### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by chowza** [eiriklv/react-masonry-component#21]
I have 12 objects in my Masonry container. Upon changing one of the objects, the entire masonry component must update.

However I'm seeing quite a significant jank as a result. When I use an ordinary container instead of a Masonry container the jank does not occur.

Any reasons why? In my 12 objects I return false in shouldComponentUpdate for 11 of them so I know only 1 rerenders, and the masonry rerenders, but I don't understand the jank that Masony is causing.

Any suggestions what may be the cause?

**Comment by afram** [comment]
The jank may be due to all the computation masonry is doing. Do you have a small test case for debugging purposes?

**Comment by afram** [comment]
@chowza I am going to close this due to inactivity. Please reopen if this is still an issue for you. :-)
