### ISSUE TITLE
Change package dependencies to peerDependencies

### ISSUE THREAD

**Issue by dkwingsmt** [eiriklv/react-masonry-component#23]
Some of the dependencies listed in ``package.json``, including ``react`` and ``react-dom``, will cause conflict and error when the project using your module is a plugin of a host project. See https://nodejs.org/en/blog/npm/peer-dependencies/  

Could you move them into ``peerDependencies``?

**Comment by afram** [comment]
@dkwingsmt The only prod dependencies this package has are imagesloaded and masonry-layout. Everything else is a dev-dependency, and shouldn't be installed when requiring the module through NPM

**Comment by afram** [comment]
Also, React is already a peer-dependency

**Comment by dkwingsmt** [comment]
You are right. My mistake when reading package.json. It might have been installed by other dependencies of mine.
