### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by afram** [eiriklv/react-masonry-component#24]
@eiriklv Firstly what do you think about adding Travis CI support in order to run tests on commit/pull request?

Second, you will have to do it, the repo is under your account.

(We could also create an org for this, but that might be overkill)

**Comment by eiriklv** [comment]
Sounds great to me :-)

**Comment by eiriklv** [comment]
I have "flicked the switch" on https://travis-ci.org, so it should be good to go

**Comment by eiriklv** [comment]
@afram Thanks for doing all this work btw :-)

**Comment by afram** [comment]
no worries we use this thing for one of our apps and we needed features from it :-)
