### ISSUE TITLE
masonry-layout 4.0

### ISSUE THREAD

**Issue by mull** [eiriklv/react-masonry-component#27]
Hi folks!

I noticed that Masonry 4.x is out, and it seems to me that it cuts file size pretty heavily by not requiring jQuery (don't quote me on that at all...) Is work being done to upgrade? I can possibly help, though I'm not familiar at all with the code base yet.

**Comment by afram** [comment]
hi @mull Yes this is in the works. Masonry 4 I believe drops support for IE8, so it'd be a major release. Will look to push it through into beta tonight/tomorrow

**Comment by moimael** [comment]
Any news on this ? :)

**Comment by afram** [comment]
This is done and published to npm as 4.0.0
