### ISSUE TITLE
how to filter selectItem just like example

### ISSUE THREAD

**Issue by cswleocsw** [eiriklv/react-masonry-component#3]
I don't know how to filter my selectItem?  Is Masonry have support filter function like Isotope ?

**Comment by eiriklv** [comment]
@cswleocsw - You should be able to filter just by using `.filter` on the array of items you are putting into your masonry :-) This is the "React way" of doing it at least

**Comment by afram** [comment]
@cswleocsw I'm going to close this as resolved. Please reopen if you still need to discuss.

**Comment by abansal3** [comment]
@eiriklv in order to filter the masonry items would each item be passed a custom prop that the filter is based on?
