### ISSUE TITLE
Preserve children order?

### ISSUE THREAD

**Issue by olalonde** [eiriklv/react-masonry-component#37]
Is there any way to prevent masonry from re-ordering elements? I don't need the "optimal" placement of elements as the order of my elements is important. All I want is for 2 elements in the same column to have no whitespace between them.

**Comment by afram** [comment]
Hi @olalonde 

Do you have a code sample we could look at all?

**Comment by afram** [comment]
@olalonde There are ways to achieve a masonry effect using CSS only - though it's a bit limited. Have you tried any of those?

**Comment by olalonde** [comment]
Thanks, I ended up cropping my images to get square thumbnails instead.
