### ISSUE TITLE
ES6 & Typescript

### ISSUE THREAD

**Issue by mbeauchamp7** [eiriklv/react-masonry-component#41]
Hi, I've been struggling to make the events work with typescript. I followed the example you gave but it just never fires. Maybe I'm doing something wrong, i don't know, I'm quite new to react and typescript/es6. Would be cool if you could provide a complete example!

Here's a small portion of the code

Thanks

```
var Masonry = require('react-masonry-component');

public handleImagesLoaded(imagesLoadedInstance) {
    this.setState({
      showImages: true
    });
  }

public render() {
    let masonryOptions = {
      transitionDuration: 0
    };

    let posts = this.state.showImages ? this.state.posts.map((post, i) => {
      return <PostComponentReact key={i} post={post}></PostComponentReact>
    }) : null;

    return (
      <section id="content">
        <div className="page pl-25 pr-25 mb-40">
          <Masonry className="row"
            ref="masonry"
            options={masonryOptions}
            onImagesLoaded={this.handleImagesLoaded}
            >

            {posts}

          </Masonry>
        </div>
      </section>
    )
  }
```

**Comment by afram** [comment]
@mbeauchamp7 The reason is that master is not yet on NPM. I will endeavour to publish version 4.1.0 asap and let you know. Sorry about that.

**Comment by mbeauchamp7** [comment]
Ahh! I knew something was wrong :) thanks. I worked around it by using the library manually like this

```
      let imgArray = [];
      nextProps.posts.forEach((img) => {
        let newImg = new Image();
        newImg.src = img.imageUrl;
        imgArray.push(newImg);
      });
      this.imgLoad = imagesloaded(imgArray);
      this.imgLoad.on('always', this.handleimagesloaded);
```

Maybe not the best way to do it but it worked..

**Comment by afram** [comment]
@mbeauchamp7 this should work for you now in v4.1.0

Please let me know if you have any issues. Closing this Issue.
