### ISSUE TITLE
masonry instance is not accessible

### ISSUE THREAD

**Issue by ybv** [eiriklv/react-masonry-component#48]
I've been trying to get a hold of masonry instance after `render()` by passing masonry via `refs` like so..

```
class List extends Component {
  componentDidMount() {
    if (this.masonry) {
      console.log(this.masonry); //  undefined
    }
   else{
     console.log(this); // can see masonry as a SubClass instance
    }
  }

  render() {
    const listItems = [items];
    return (<Masonry
      ref={c => this.masonry = c.masonry}
      className={'my-grid-class'}
      elementType={'ul'}
      options={masonryOptions}
      disableImagesLoaded={false}
      updateOnEachImageLoad={false}
    >
    {listItems}
    </Masonry>);
  }
}
```

Not sure what I'm missing here. Would be awesome if you can get a chance to help out.
/cc @eiriklv

**Comment by kyleicebreaker** [comment]
you need to bind the function you pass into ref to _this_

ref={function(c) {this.masonry = c.masonry}.bind(this)}

**Comment by afairbrother** [comment]
Despite binding the function to this there is still an error in the console. `Uncaught TypeError: Cannot read property 'masonry' of null`

**Comment by alwynsays** [comment]
I've relegated to doing something like:

``` javascript
<Masonry ref="masonry" ... />
```

And to reference in another method within the component:
``` javascript
componentWillReceiveProps() {
  this.refs.masonry.performLayout()
}
```

**Comment by afairbrother** [comment]
Ah, thanks @alwynsays, this worked for me

**Comment by UgRoss** [comment]
[From React Docs](https://facebook.github.io/react/docs/more-about-refs.html): 

> Although string refs are not deprecated, they are considered legacy, and will likely be deprecated at some point in the future. Callback refs are preferred.

You can do it like this:
```javascript
<Masonry ref={c => this.masonry = c} ... />
```

and

```javascript
componentWillReceiveProps() {
  this.masonry.performLayout()
}
```

**Comment by afram** [comment]
@ybv not sure why this isn't working for you. It's working fine for me and my code looks very similar to yours. 

What versions of React/react-masonry-component/babel are you using?

**Comment by afram** [comment]
I'm closing this issue. Please reopen if needed.
