### ISSUE TITLE
Unknown proptypes passed down to elementType node.

### ISSUE THREAD

**Issue by Exomnius** [eiriklv/react-masonry-component#49]
Since react v15.2.0, you will get a warning when you pass a prop, that is not in the proptypes, to a DOM node. 

Example:

```
<Masonry
  ref="masonry"
  className={'grid'}
  elementType={'ul'}
  options={masonryOptions}
  disableImagesLoaded={false}>
 {/* Other code */}
</Masonry>
```

Gives the following warnings:
Warning: Unknown props `elementType`, `options`, `disableImagesLoaded` on ul tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by afram** [comment]
Ta, will get this sorted out asap.

**Comment by afram** [comment]
@Exomnius What version of react-masonry-component are you using?

This should have been sorted from version 4.2.0

**Comment by Exomnius** [comment]
Thanks for the reply! It seems to be resolved now. A clean checkout and rebuild fixed it so it was probably an older version.

**Comment by afram** [comment]
No worries @Exomnius
