### ISSUE TITLE
Error occur on IE

### ISSUE THREAD

**Issue by homs44** [eiriklv/react-masonry-component#66]
return {
            old: knownChildrenStillAttached, // Not used
            new: currentDomChildren, // Not used
            removed: removed,
            appended: appended,
            prepended: prepended,
            moved: moved,
            //forceItemReload <- this code occur error on IE (message : ' : ' is required) 
         forceItemReload:forceItemReload
};

**Comment by afram** [comment]
Looks like an issue with a recent change. Thanks for bringing it up. Will look at it tonight

**Comment by arpecop** [comment]
fixing all warning solved this , also moving the module outside the npm_modules and accessing it via './react-masonry-component'

**Comment by afram** [comment]
This issue is due to es6 syntax used in the index.js file. Has been committed to master and will be published soon.

**Comment by afram** [comment]
Can you please verify 5.0.2 fixes this for you?

**Comment by homs44** [comment]
Hi i check the lib but there is another error
I run my web using this lib on IE 9
maybe the problem is let statement 

diffDomChildren :function(){
 let forceItemReload = false <- error

**Comment by afram** [comment]
Yes you are right.

**Comment by afram** [comment]
5.0.3 should sort it out.

I've also added eslint to avoid this happening in future.

Can you please verify?

**Comment by afram** [comment]
closing. Please reopen if needed.
