### ISSUE TITLE
webpack production build - SyntaxError

### ISSUE THREAD

**Issue by finbarmaginn** [eiriklv/react-masonry-component#67]
I'm no expert and understand that raising this as an issue may not be the correct thing to do, I just cannot get it to work.

The plugin works fine in my dev build process but when trying to compile for production i'm getting this error.
```
ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected token: name (forceItemReload) [./~/react-masonry-component/lib/index.js:68,0]
```
The error is coming from UglifyJs so could it be something to do with my webpack config? see below for the uglify plugin configuration that i've been using to minify react.
```
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        screw_ie8: true
      }
    })
```

**Comment by afram** [comment]
Looks like an issue with a recent change. Thanks for bringing it up. Will look at it tonight

**Comment by afram** [comment]
Should hopefully be fixed in 5.0.2 

Can you please verify?

**Comment by afram** [comment]
Sorry, can you please try 5.0.3 instead?

**Comment by finbarmaginn** [comment]
I can confirm that 5.0.3 is working. Thanks for a quick turnaround!
