### ISSUE TITLE
Position left to all elements is 0 when first element is wider than other

### ISSUE THREAD

**Issue by DimaNodeJs** [eiriklv/react-masonry-component#68]
Everything the same except position of wide element in array. Masonry is initialized but work incorrect. All elements have position-left 0...

<img width="1369" alt="2017-02-01 22 16 28" src="https://cloud.githubusercontent.com/assets/20300753/22522344/486c9a40-e8cc-11e6-8bfb-3305c5c2d6a7.png">
<img width="1548" alt="2017-02-01 22 15 18" src="https://cloud.githubusercontent.com/assets/20300753/22522345/486fd214-e8cc-11e6-8e18-cae725465999.png">

Hope for quick reply. tnx)

**Comment by afram** [comment]
Hi @DimaNodeJs 

Which version of react-masonry-component are you using?

Still at work right now, will do my best to look at this tonight with you.

**Comment by afram** [comment]
Can you please paste up a simple reproduction of this issue on WebpackBin?

http://www.webpackbin.com/

**Comment by DimaNodeJs** [comment]
@afram  "version": "5.0.3"

```
import React from 'react';
import GridItem from './item';
import classnames from 'classnames';
import Masonry from 'react-masonry-component';


const Grid = ({ items, masonry }) => {
  const masonryOptions = {
    transitionDuration: '0.6s'
  };

  if (items.length) { items = items.map(GridItem) }

  return (
    <div className={classnames('b-grid', {[`b-grid--masonry`]: masonry})} >
      { masonry ? <Masonry options={masonryOptions} >{ items }</Masonry> : items }
    </div>
  )
};

export default Grid;
```

Could it be helpful? it's almost exactly the same code I use. Mb you can find something strange in my code.
If not I'll create an example later in several hours.

**Comment by DimaNodeJs** [comment]
I think I had to set `columnWidth` property equal to smaller item. 
But there is no information about it in docs(( 
btw thx for really quick reply and aspiration to help! )

**Comment by afram** [comment]
no problem. columnWidth would be from Masonry's side. Can I close this now as resolved?

**Comment by afram** [comment]
closing. Please reopen if needed.
