### ISSUE TITLE
How can I use the Masonry method `stamp`?

### ISSUE THREAD

**Issue by goyney** [eiriklv/react-masonry-component#69]
I need to stamp certain items in my grid, but cannot determine how to use the `stamp` method [defined in the official Masonry documentation](http://masonry.desandro.com/methods.html#stamp).

Is this supported or is there a workaround which can allow this method to be utilized?

**Comment by afram** [comment]
Hi @goyney 

You can access the masonry instance and use the stamp method.

https://github.com/eiriklv/react-masonry-component#accessing-masonry-instance

**Comment by goyney** [comment]
I'd be interesting in seeing a working example, because utilizing the linked section of documentation does not allow the use of the stamp method.

**Comment by afram** [comment]
http://www.webpackbin.com/N16LfRY_f

**Comment by afram** [comment]
can I close this @goyney

**Comment by afram** [comment]
I'm closing. Please reopen if needed.

**Comment by jrock17** [comment]
Can you add a working example of stamp to the docs? The Webpack above does not work. Thanks.
