### ISSUE TITLE
Render issue (probably on slow connection)

### ISSUE THREAD

**Issue by indapublic** [eiriklv/react-masonry-component#71]
Example:

![screen shot 2017-02-21 at 10 53 11](https://cloud.githubusercontent.com/assets/856260/23146596/04ef7262-f824-11e6-8ad0-e28c100609cb.png)

How I can to fix it?

**Comment by afram** [comment]
@indapublic What do your masonry settings look like and can you provide a code example? Preferably on something like webpackbin
