### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16

### ISSUE THREAD

**Issue by conghai** [eiriklv/react-masonry-component#74]
> Warning: MasonryComponent: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement

[https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass)

Please check it.

**Comment by MrSauceman** [comment]
Same thing here, I'm surprised react throws this warning for an installed dependency...

**Comment by Fensterbank** [comment]
`index.js` needs to be rewritten in ES2015 to avoid this warning.
In fact this should be pretty easy, the component isn't very complex, but we need to upgrade / change the build tools to make this work with ES2015 and JSX.

**Comment by afram** [comment]
Should be fixed in v5.0.5

**Comment by arpecop** [comment]
npm update
pix@1.0.0 /Users/rudix/Desktop/arpecop/_apps/pix
└── react-masonry-component@5.0.5
wow guys , just wow

**Comment by afram** [comment]
@arpecop can you elaborate?

**Comment by arpecop** [comment]
No, actually I am amazed by the efforts you put in something   "open source" , this React update is pretty new and "Warnings" are too much to keep count and understand them ... not the case with this module 
Thanks!

**Comment by afram** [comment]
That's great to hear, thanks @arpecop!
While I've got your attention, did my comment help you with https://github.com/eiriklv/react-masonry-component/issues/65?
