### ISSUE TITLE
Turn off the animation when it first appears

### ISSUE THREAD

**Issue by yueduz** [eiriklv/react-masonry-component#75]
Request function

**Comment by afram** [comment]
@yueduz can you please elaborate on this request? I'm not quite sure what you want :-)

**Comment by yueduz** [comment]
I do not speak English, i use google translation. I want to disable the playing animation.

**Comment by Ganasist** [comment]
I think I want what he's also asking about:

Is it possible to suppress the animation on initial load, and only have it animate thereafter? For initial load I just want my items to appear immediately in-place.

**Comment by afram** [comment]
Well this is just a wrapper over the Masonry library. Try setting transitionDuration to zero.

https://masonry.desandro.com/options.html

Play around with the options. Hard to help further without seeing your code.

Hope this helps!

**Comment by FullstackJack** [comment]
Yes, the animation is stupid and probably making this less performant than it needs to be.
