### ISSUE TITLE
Looking for exemples

### ISSUE THREAD

**Issue by Hydeo** [eiriklv/react-masonry-component#78]
Hi there ! 

First sorry for the issue-oppening ! =/

I'm working on my first React project and Masonry is kind of magic for me right now, i'm trying to figure out how to use react-masonry and i'm in a desesperate need of exemples.

I'm trying to get something like the layout found in the exemple : http://www.hearsay.me/
I can't find the source of it, doesn't anybody knows where i can find there or any other kind of exemples ?

Thanks for reading me, sorry again for the bother and have a nice day :)

**Comment by afram** [comment]
Hi @Hydeo The examples are in the Readme. Under the hood it's just Masonry. Please let me know if there's anything in the README that isn't clear.

**Comment by afram** [comment]
Hi @Hydeo 

I'm going to close this issue. Please feel free to reopen if needed :-)
