### ISSUE TITLE
option horizontalOrder is missed

### ISSUE THREAD

**Issue by rjohnep** [eiriklv/react-masonry-component#79]
Hi @eirikl,
Can you update dependencies for 'masonry-layout' (4.2.0) and add ['horizontalOrder'](http://masonry.desandro.com/options.html#horizontalorder) option?
Thanks.

**Comment by nguymin4** [comment]
Hi @afram could you consider this? Thanks.

**Comment by afram** [comment]
@rjohnep @nguymin4 You can already do this.

The horizontalOrder property is a Masonry option, you can just add it to your existing Masonry options.

I have also added the option to the TypeScript interface and bumped the min version of masonry-layout to 4.2.0 - It shouldn't make a difference for you unless you are using TypeScript.

I'm going to close this issue. Please reopen if needed.

Here's an example on how you'd use `horizontalOrder`.

```javascript
import React from 'react'
import Masonry from 'react-masonry-component';

const masonryOptions = {
    transitionDuration: 0,
    horizontalOrder: true
};

class Gallery extends React.Component {
    render() {
        const childElements = this.props.elements.map(function(element){
           return (
                <li className="image-element-class">
                    <img src={element.src} />
                </li>
            );
        });

        return (
            <Masonry options={masonryOptions}>
                {childElements}
            </Masonry>
        );
    }
};
```

**Comment by afram** [comment]
Should add that 5.0.7 has been released with the changes mentioned above.

**Comment by johnantoni** [comment]
Hi @afram, checked the latest release and doesn't appear to be there. Any chance of adding this in?
