### ISSUE TITLE
There is a way to recalc height?

### ISSUE THREAD

**Issue by witalobenicio** [eiriklv/react-masonry-component#81]
I have 3 components inside <Masonry> and I want to recalculate the height setted to the container when all 3 components have finished loading.
How can I do that?

**Comment by afram** [comment]
If I understand you correctly you want to work out what the container height is after layout is complete?

If that's so, you could listen to the `layoutComplete` event on the underlying Masonry instance.

https://masonry.desandro.com/events.html#layoutcomplete

Does that do what you want?

**Comment by afram** [comment]
Hi @witalobenicio,

I'm going to close this issue. Please feel free to reopen if needed :-)

**Comment by afram** [comment]
Hi @witalobenicio,

I'm going to close this issue. Please feel free to reopen if needed :-)
