### ISSUE TITLE
TypeError: this.masonry.off is not a function

### ISSUE THREAD

**Issue by sarukuku** [eiriklv/react-masonry-component#83]
We're getting this kind of error sometimes when navigating between views in our react app. It seems to happen randomly and I'm suspecting its some kind of a race condition.

![screen shot 2017-06-07 at 10 29 21](https://user-images.githubusercontent.com/1204559/26867221-2e061128-4b6d-11e7-9d0c-16c1bf7d12b5.jpg)

**Comment by sarukuku** [comment]
@afram any ideas? :)

**Comment by afram** [comment]
Do you have a code sample I could look at? @sarukuku

**Comment by sarukuku** [comment]
@afram not really, sorry :( It's a bigger company project and I unfortunately don't have the time to try to reduce the project to a minimal test case. I was seeing this a lot in the last version of our platform but I haven't seen this in the current development branch at all. It might well be that the error has been triggered by a bug in some dependency.

From my point of view you can close this. I can reopen the issue if I run into the issue again. At least it's here if someone googles for a similar issue.

**Comment by bartdominiak** [comment]
Can you reopen this issue? I handle with this error also.

**Comment by afram** [comment]
@bartdominiak can you please provide a code example where this is happening?

I can not reproduce and without broken code there isn't much I can do really :-)
