### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by evandavis** [eiriklv/react-masonry-component#90]
I'm trying to do a standalone AMD build of this repo. I notice you include `webpack` in `devDependencies` but not the `webpack.config.js`. Do you have a build configuration you could include?

**Comment by afram** [comment]
I'm terribly sorry, I don't use AMD anymore and don't have a plan to support it.

As for the webpack config, this project has the config tied in with the Karma config as it's only used for testing.

https://github.com/eiriklv/react-masonry-component/blob/master/spec/setup/karma.conf.js

Hope this helps.

**Comment by evandavis** [comment]
I didn't even think to look there. That got me what I needed, thanks!
