### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by jcguarinpenaranda** [eiriklv/react-masonry-component#92]
Hello,

Just wanted to tell you that the example is not working due to failing CORS

![captura de pantalla 2017-08-14 a las 11 50 53 a m](https://user-images.githubusercontent.com/7200821/29282044-f2fd7bfc-80e6-11e7-901e-5579ed9e16ad.png)

**Comment by afram** [comment]
Hi @jcguarinpenaranda 

Looks like this issue is fixed now. Does it work for you now?

I'm closing this issue for now, please feel free to reopen if needed :-)
