### ISSUE TITLE
Useless complete items reload

### ISSUE THREAD

**Issue by mbeauchamp7** [eiriklv/react-masonry-component#95]
I was digging in the source code to find out why my whole list was reloading when only a property of an item was changing and I found that no matter if there were appended/prepended/moved etc, it was still reloading it all.

If you look [here](https://github.com/eiriklv/react-masonry-component/blob/master/lib/index.js#L88) you can see that we are comparing the length of the previous know childrens (number) with the current known childrens (array) therefor always thruthy.

**Comment by afram** [comment]
Should be fixed in v6.0.0

Please let me know if it works for you.

sorry again for the delay in merging in your PR.

**Comment by mbeauchamp7** [comment]
Better late than never! Thanks @afram
