### ISSUE TITLE
Element ref was specified as a string (masonryContainer)

### ISSUE THREAD

**Issue by hurrtz** [eiriklv/react-masonry-component#98]
Hey guys,

I think there might be an issue with environments running React 16 and using masonrycomponent, which by itself runs React 15.

I get the error "Uncaught (in promise) Error: Element ref was specified as a string (masonryContainer) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner)." which is pretty brutal as this kills the entire app. React completely stops working.

Can you please look into this? The relevant parts in my package.json:
"react": "^16.0.0"
"react-dom": "^16.0.0"
"react-masonry-component": "^5.0.7"

As soon as I have reverted React back to the version you have in your own package.json everything worked again.

**Comment by afram** [comment]
Yes you are right. This needs to be updated.

**Comment by afram** [comment]
This should now be fixed in v6.0.0

Please let me know if it works for you.

Closing this ticket, though please open again if needed!
